name: boardgames CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code.
        uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - name: Build & install dependencies.
        run: npm install
      - name: Run Unit tests on our WebApp.
        run: npm run test:unit
      - name: Display my SoftUni username.
        run: echo "qceka88"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy our WebApp to  production.
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
    needs: build-test

  run-ui-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code.
        uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - name: Build & install dependencies.
        run: npm install
      - name: Install playwright module for UI tests.
        run: npx playwright install
      - name: Run User Interface tests.
        run: npm run test:ui
    needs: deploy